# ────────────────────────────────────────────────────────────
# Omarchy Matte Black Theme for Alacritty
# By tahayvr
# https://github.com/tahayvr
# ────────────────────────────────────────────────────────────

[window]
# window padding {px}
padding.x = 12
padding.y = 12

[font]
size = 12.0



[colors]
[colors.primary]
background = "#111314"
foreground = "#F7F3EA"
dim_foreground = "#8a8a8d"

[colors.cursor]
text = "#111314"
cursor = "#F7F3EA"

[colors.vi_mode_cursor]
text = "#111314"
cursor = "#eaeaea"

[colors.selection]
text = "#111314"
background = "#A2AE61"

[colors.normal]
black = "#232525"
red = "#ea6962"
green = "#a9b665"
yellow = "#e7ac4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#F7F3EA"

[colors.bright]
black = "#232525"
red = "#ea6962"
green = "#a9b665"
yellow = "#e7ac4e"
blue = "#7daea3"
magenta = "#d3869b"
cyan = "#89b482"
white = "#F7F3EA"
